# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Container Build
permissions: read-all
on:
  push:
  workflow_dispatch:
jobs:
  # https://github.com/intel/ai-containers/blob/main/.github/action.yml
  build-containers:
    runs-on: docker # does not support node20
    env:
      http_proxy: ${{ secrets.HTTP_PROXY }}
      https_proxy: ${{ secrets.HTTPS_PROXY }}
      REGISTRY: ${{ secrets.REGISTRY }}
      REPO: ${{ secrets.REPO }}
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: docker/login-action@v2.2.0
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Build Containers
        run: |
          docker compose -p ${GITHUB_RUN_NUMBER} up --build --no-start
        working-directory: .github/workflows/docker
      - name: Print Containers to Summary
        run: |
          docker compose -p ${GITHUB_RUN_NUMBER} images --format json | jq -r --arg registry "$REGISTRY" '.[] | select(.Repository | contains($registry)) | .Tag' >> $GITHUB_STEP_SUMMARY
      - name: Push Containers
        run: |
          docker compose -p ${GITHUB_RUN_NUMBER} push
        working-directory: .github/workflows/docker
      - name: Un-Tag Containers
        run: |
          docker compose -p ${GITHUB_RUN_NUMBER} down --rmi all
        working-directory: .github/workflows/docker
      - name: Remove Containers
        if: always()
        run: docker system prune --force
