# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Check for missing Dockerfile paths in repo comps

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *' # Runs at 5 PM UTC every day

jobs:
  check-dockerfile-paths:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo GenAIExamples
      uses: actions/checkout@v4

    - name: Clone repo GenAIComps
      run: |
        git clone https://github.com/opea-project/GenAIComps.git ..

    - name: Check for missing Dockerfile paths in GenAIComps
      run: |
        grep -Ern 'docker build .* -f comps/.+/Dockerfile' --include='*.md' . | while IFS=: read -r file line content; do
            dockerfile_path=$(echo "$content" | awk -F '-f ' '{print $2}' | awk '{print $1}')
            if [[ ! -f "../GenAIComps/${dockerfile_path}" ]]; then
                echo "Missing Dockerfile: ${dockerfile_path} (Referenced in ${file}:${line})"
            fi
        done
      shell: bash
